#configuration.yaml
# base conf
homeassistant:
  time_zone: "Asia/Tokyo"
  country: JP
  currency: JPY
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  media_dirs:
    media: /media

# configure trusted proxy for traefik
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.13.89.90 # host
    - 172.16.0.0/12 # docker bridge networks (incl. homelab_proxy)

# custom oidc integration from HACS (https://github.com/christiaangoossens/hass-oidc-auth)
auth_oidc:
  client_id: !secret client_id
  client_secret: !secret client_secret
  discovery_url: !secret discovery_url


# add themes folder
frontend:
  themes: !include_dir_merge_named themes

# includes
# group: !include groups.yaml
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml
# sensor: !include sensors.yaml